name: "Blog of Mackail"
description: "Web Front-End Blog by mackail"
url: "http://www.mackail.me"
timezone: Asia/Shanghai

paginate: 16
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

gems:
- jekyll-paginate

# Comment setting
comments :
  provider : duoshuo
  duoshuo :
    short_name : mackail